README.markdown

I feel like the example would be best using http://www.ruby-doc.org/core-2.2.0/Marshal.html not madeline.
No need to pull in extra dependencies when the standard library has got us covered, :).
Maybe using redis is a bad example and it should just write to a file?

Remove references to Madeline

---

.travis.yml
classifier-reborn.gemspec

Test unit has been removed from the standard lib as of 2.2.0, so it must be required to run tests.

test unist is no longer in std lib, needs to be required in dev and test

---

lib/classifier-reborn/lsi.rb

Warnings produced when doing `jekyll build` were:
warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
The warnings are supressed when using `.eql?` method.
jekyll (2.5.3)
classifier-reborn (2.0.3)
rb-gsl (1.16.0.4)

Fix lsi.rb Comparable#== warning

---

lib/classifier-reborn/bayes.rb
lib/classifier-reborn/lsi.rb
test/bayes/bayesian_test.rb
test/lsi/lsi_test.rb

I've been using a monkeypatch similar to this on the old classifier for years to help with various kinds of keyword research... hoping to get it (and eventually several others) included upstream with the classifier rebirth

Add methods for classifying and returning the score as well

---

lib/classifier-reborn/extensions/hasher.rb

This is a set of simple performance improvements for the Hasher process. Picking a random wikipedia page and hashing it 200 times, I get the following improvements before/after (excluding the Set regression, it was a set before my last PR). Additionally, it fixes broken regex splitting for non-ascii characters and removes the unused punctuation filter.
```
BEFORE
user     system      total        real
times:    4.400000   0.010000   4.410000 (  4.403278)
AFTER
user     system      total        real
times:    2.630000   0.010000   2.640000 (  2.632828)
```

Hasher performance

---

lib/classifier-reborn/extensions/hasher.rb
lib/classifier-reborn/extensions/vector.rb
lib/classifier-reborn/lsi.rb
lib/classifier-reborn/lsi/content_node.rb
lib/classifier-reborn/lsi/summarizer.rb

This eliminates several Ruby :warning:s when run with `RUBYOPT="-w"`.

Ruby warnings

---

lib/classifier-reborn/bayes.rb
lib/classifier-reborn/category_namer.rb
test/bayes/bayesian_test.rb

Few things got done here:
* Set up a few things to use default hash values
* made auto-categorization optional, defaulting to false
* Fixed the bug where adding the same category a second time would completely clobber the category that was already there
* If a category name is already a symbol, just return it

Default hash cleanup

---

lib/classifier-reborn/lsi.rb
lib/classifier-reborn/lsi/cached_content_node.rb
lib/classifier-reborn/lsi/content_node.rb
test/lsi/lsi_test.rb

Lot of little things here that add up but I'll try to summarize:
* Reduce some unnecessary methods
* Add optional CachedContentNode (GSL only)
* Caches the transposed search_vector
* Has custom marshal_ methods to not save the cache when dumping/loading
* Transparently compatible with pure ruby
* Optimized some numeric comparisons and iterators
* Added cached calculation table when computing raw_vectors
I'm not exactly sure how much faster this is, much of it depends on the size/nature of your corpus and the classifications you are making but for me at around 150 documents and thousands of classifications, its somewhere around 600%.
Its a bit awkward to test things .. currently the gemspec has to have gsl added in order to test the GSL variants, but it is what it is. Maybe somebody else …

Bunch of performance fixes and speedups

---

lib/classifier-reborn/extensions/hasher.rb
test/bayes/bayesian_test.rb

Fix encoding error for ruby 1.9.3 for issue #49

---

README.markdown

Added documentation to the README file to support the new threshold feature.

documented new threshold feature

---

lib/classifier-reborn/bayes.rb
lib/classifier-reborn/extensions/hasher.rb
test/bayes/bayesian_test.rb
test/extensions/hasher_test.rb

Adds an option to the bayesian classifier to disable word stemming. This is necessary for use cases where two words that are stemmed to the same root should actually be classified differently.

Option to Disable Stemming

---

lib/classifier-reborn/extensions/hasher.rb
test/extensions/hasher_test.rb

Per discussion in [Functionality to modify stopword lists?](https://github.com/jekyll/classifier-reborn/issues/72) thread. I added a method to hasher module so users can add a custom path to a directory with user-made stopword files.
```
def add_custom_stopword_path(path)
STOPWORDS_PATH.unshift(path)
end
```
Not sure it adds a tonne of value over the current way to hack it,
**Current:**
```
include ClassifierReborn
Hasher::STOPWORDS_PATH.unshift("/home/ubuntu/workspace/data")
```
But I think it makes adding a path slightly more intuitive for someone not digging into the code.
**Updated:**
```
include ClassifierReborn
Hasher.add_custom_stopword_path("/home/ubuntu/workspace/data")
```
Thoughts?

Method to add custom path to user-created stopword directory

---

lib/classifier-reborn/lsi.rb
test/lsi/lsi_test.rb

This pull request should handle issues #64 and #75, mostly by throwing up human-readable error messages. Error messages aren't cool, but they're more graceful than programs crashing.
Issue #64 is caused by adding "invalid" documents beforehand, and we resolve this by rejecting those "invalid" documents before they could cause problems later on for the end-user. If you try to search a corpus of documents that include "invalid" documents, the program will crash. If you try to find related phrases, it _won't_ crash and you'll still get results. However, I would still recommend rejecting "invalid" documents outright because these invalid documents adds noise that can narrowly impact the LSI's results.
Issue #75 is caused by attempting to search through a corpus for a term that does not exist …

Fix searching issues with classifier-reborn

---

README.markdown

I had to dig through the code to figure out why this example was
failing.
I guess this option was added later, and was previously the default

Updates readme example

---

README.markdown
lib/classifier-reborn/extensions/hasher.rb

Forching UTF-8 encoding when reading stopwords, fixes #82

Stopword encoding

---

.travis.yml
Gemfile
README.markdown
lib/classifier-reborn/backends/bayes_memory_backend.rb
lib/classifier-reborn/backends/bayes_redis_backend.rb
lib/classifier-reborn/bayes.rb
test/backends/backend_common_tests.rb
test/backends/backend_memory_test.rb
test/backends/backend_redis_test.rb
test/bayes/bayesian_common_tests.rb
test/bayes/bayesian_redis_test.rb
test/bayes/bayesian_test.rb

Memory and Redis backend support

---

.gitignore
test/bayes/bayesian_common_tests.rb
test/bayes/bayesian_integration_test.rb
test/bayes/bayesian_redis_test.rb
test/data/corpus/README.md
test/data/corpus/SMSSpamCollection.tsv

Adding some integration test based on real dataset as discussed in #84.

Bayes integration test of Memory and Redis backends with real data

---

test/backends/backend_redis_test.rb
test/bayes/bayesian_integration_test.rb
test/bayes/bayesian_redis_test.rb

Disabled Redis disc persistence and refactored integration test

---

test/bayes/bayesian_common_benchmarks.rb
test/bayes/bayesian_integration_test.rb
test/bayes/bayesian_memory_benchmark.rb
test/bayes/bayesian_redis_benchmark.rb
test/data/test_data_loader.rb
test/test_helper.rb

* Refactored benchmark code to reduce the number of reads of the data file
* Added SpecReporter that shows each test case name grouped with suit names instead of the default progress bar that was not very informative
* Added custom reporter for benchmarks to better represent the information in a copy paste friendly format -- bye bye `NOPROGRESS` ENV hack
* Added record counts on which benchmarks were performed

Benchmark refactoring, improving efficiency, enhanced reporting

---

Dockerfile
test/bayes/bayesian_common_benchmarks.rb

By moving the less frequently changing independent layer up, we can utilize cache to speed up the image building process.

Speed up Docker image rebilding

---

Dockerfile

With #96 in place, adding `redis` gem in the Dockerfile is no longer needed.

Removed redis gem from Dockerfile as it is added in gemspec

---

.gitignore
Dockerfile
docs/_config.yml
docs/bayes.md
docs/development.md
docs/index.md
docs/lsi.md

I have created a basic static documentation site. We need to add navigation among pages, currently only the home page links to other pages. The text is mostly the same as current README, except a few places that are modified to better unify the style. And in few places more text is added. In order for it to be served properly, the repo needs to be configured to serve static pages from the `docs` folder of the master branch. This idea was first tossed in #95.

Created a static site for documentation

---

lib/classifier-reborn/backends/bayes_memory_backend.rb
lib/classifier-reborn/backends/bayes_redis_backend.rb
lib/classifier-reborn/bayes.rb

Added/corrected necessary RDoc documentation after backend support.

Added and corrected RDoc for ceratin classes and methods

---

README.markdown
docs/index.md
docs/lsi.md

Only the essential getting started stuff along with repo status buttons are left in the README. For the rest of the content pointers are added to the documentation site.

README file cleaned up to point to the documentation site

---

History.markdown
docs/bayes.md
lib/classifier-reborn/bayes.rb
test/bayes/bayesian_common_tests.rb
test/bayes/bayesian_memory_test.rb
test/bayes/bayesian_redis_test.rb
test/data/stopwords/en

Abbility to add custom stopwords at classifier initialization

---

test/bayes/bayesian_common_tests.rb
test/bayes/bayesian_memory_test.rb
test/bayes/bayesian_redis_test.rb

There was a lot of duplicate login in both backend tests which is now refactored and moved to the common file.

Refactoring of backend tests to move duplicate login in the common file

---

lib/classifier-reborn/bayes.rb

Makes the return value of `train` and `untrain` methods useful by returning the total training count of the given category. Returns `nil` when training/untraining is skipped due to empty `word_hash`. Related to #130 and #135.

Return the startus of the training/untraining when run

---

README.markdown
docs/bayes.md
docs/index.md

Removed magic `train_*` and `untrain_*` methods and other documentation cleanup. #140

Removed magic train untrain methods from docs, #140

---

lib/classifier-reborn/backends/bayes_memory_backend.rb
test/backends/backend_memory_test.rb

I got error `TypeError: can't dump hash with default proc` on trying to `Marshal.dump` for trained classifier. This PR fixes dumping for memory backend and adds a test for this regression.

Fixed persistance for BayesMemoryBackend

---

lib/classifier-reborn/backends/bayes_redis_backend.rb
lib/classifier-reborn/bayes.rb
test/test_helper.rb

I have tried to use the gem without using redis and got this error
```
Bundler::GemRequireError: There was an error while trying to load the gem 'classifier-reborn'.
Gem Load Error is: uninitialized constant NoRedisError
Backtrace for gem load error is:
/mnt/d/documents/projects/classifier-reborn/lib/classifier-reborn/backends/bayes_redis_backend.rb:4:in `rescue in <top (required)>'
/mnt/d/documents/projects/classifier-reborn/lib/classifier-reborn/backends/bayes_redis_backend.rb:1:in `<top (required)>'
/mnt/d/documents/projects/classifier-reborn/lib/classifier-reborn/bayes.rb:9:in `require_relative'
/mnt/d/documents/projects/classifier-reborn/lib/classifier-reborn/bayes.rb:9:in `<top (required)>'
/mnt/d/documents/projects/classifier-reborn/lib/classifier-reborn.rb:29:in `require_relative' …
```

Fixed error on requiring 'classifier-reborn' without using Redis

---

lib/classifier-reborn/backends/bayes_redis_backend.rb
lib/classifier-reborn/bayes.rb

`require_relative 'backends/bayes_redis_backend'` was removed from bayes.rb because of https://github.com/jekyll/classifier-reborn/pull/146, but having to manually `require 'classifier-reborn/backends/bayes_redis_backend'` is kind of annoying.
Putting `require 'redis'` inside BayesRedisBackend#initialize is a solution, but it's kind of gross. 
Maybe there is a better one?

Require bayes_redis_backend

---

lib/classifier-reborn/backends/bayes_redis_backend.rb

My use case is to train a model in Redis and then periodically reconnect to the model to classify a thing. For some reason every time I would reconnect, classifications have confidences of Infinity. Then I found out that initializing a BayesRedisBackend was resetting the total_words and total_trainings keys.

Set Redis keys only if they don't exist

---

classifier-reborn.gemspec

I saw an error when I tried to run test, as:
```
$ bundle exec rake test
/var/lib/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/rubygems_integration.rb:64:in `rescue in validate': The gemspec at /home/piro/projects/classifier-reborn/classifier-reborn.gemspec is not valid. Please fix this gemspec. (Gem::InvalidSpecificationException)
The validation error was '"www.classifier-reborn.com" is not a URI'
from /var/lib/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/rubygems_integration.rb:60:in `validate'
from /var/lib/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/source/path.rb:154:in `validate_spec'
from /var/lib/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/source/path.rb:168:in `block in load_spec_files'
from /var/lib/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/source/path.rb:162:in `each'
from …
```

Fix invalid URI

---

lib/classifier-reborn/extensions/vector.rb
lib/classifier-reborn/extensions/zero_vector.rb
lib/classifier-reborn/lsi.rb
test/extensions/matrix_test.rb
test/extensions/zero_vector_test.rb
test/lsi/lsi_test.rb

I've tried doing
- avoid zero division & zero vector normalization
- prevent an indeterminate form from being generated (by `0.0 / 0.0` )

Fix the corner cases

---

Rakefile
classifier-reborn.gemspec
docs/bayes.md
lib/classifier-reborn/bayes.rb
lib/classifier-reborn/extensions/hasher.rb
lib/classifier-reborn/extensions/token_filter/stemmer.rb
lib/classifier-reborn/extensions/token_filter/stopword.rb
lib/classifier-reborn/extensions/token_filter/symbol.rb
lib/classifier-reborn/extensions/tokenizer/token.rb
lib/classifier-reborn/extensions/tokenizer/whitespace.rb
lib/classifier-reborn/lsi.rb
test/bayes/bayesian_memory_test.rb
test/bayes/bayesian_redis_test.rb
test/extensions/hasher_test.rb
test/extensions/token_filter/stemmer_test.rb
test/extensions/token_filter/stopword_test.rb
test/extensions/token_filter/symbol_test.rb
test/extensions/tokenizer/token_test.rb
test/extensions/tokenizer/whitespace_test.rb

Now I'm trying to separate tokenizing operations from the hasher, as the first step for #131. I introduced these new modules and classes:
* `Tokenizer::Whitespace`
* `Tokenizer::Token`
* `TokenFilter::Stopword`
* `TokenFilter::Stemmer`
For testability and flexibility, they are stayed separated for now. Next step, I'm planning to introduce some mechanism to switch the tokenizer and related modules.
How about this approach?

Separate tokenizer from hasher

---

README.markdown
classifier-reborn-jruby.gemspec
classifier-reborn.gemspec

Now that we are using the default GitHub pages domain, referenced in the README and other pages are changed accordingly. This closes #186.

Update references to the new documentation homepage

---

docs/bayes.md

Fixed typo in Bayes documentation where `TokenFilter` was documented as `TokenFilters`

Updated Bayes docs for filters

---

.github/workflows/ci.yml
test/lsi/lsi_test.rb

classifier-reborn is designed to work with or without
[GSL](https://www.gnu.org/software/gsl/) support.
https://github.com/jekyll/classifier-reborn/blob/99d13af5adf040ba40a6fe77dbe0b28756562fcc/docs/index.md?plain=1#L68
If GSL is installed, classifier-reborn will detect it and use it. If GSL
is not installed, classifier-reborn will fall back to a pure-ruby
implementation. The mechanism for doing so is in `lsi.rb`:
https://github.com/jekyll/classifier-reborn/blob/99d13af5adf040ba40a6fe77dbe0b28756562fcc/lib/classifier-reborn/lsi.rb#L7-L17
I think it's important to test the classifier-reborn gem with GSL
support in CI. One of my goals is to add similar support using Numo,
and I'd like that to be tested in CI as well. Also, I want to make sure I
don't do anything along the way that could …

Test Native and GSL Implementations

---

.github/workflows/ci.yml
.rubocop.yml
Gemfile
docs/index.md
lib/classifier-reborn/lsi.rb
lib/classifier-reborn/lsi/content_node.rb
test/extensions/matrix_test.rb
test/extensions/zero_vector_test.rb
test/lsi/lsi_test.rb

**Background:**
The slow step of LSI is computing the SVD (singular value decomposition)
of a matrix. Even with a relatively small collection of documents (say,
about 20 blog posts), the native ruby implementation is too slow to be
usable (taking hours to complete).
To work around this problem, classifier-reborn allows you to optionally
use the `gsl` gem to make use of the [Gnu Scientific
Library](https://www.gnu.org/software/gsl/) when performing matrix
calculations. Computations with this gem perform orders of magnitude
faster than the ruby-only matrix implementation, and they're fast enough
that using LSI with Jekyll finishes in a reasonable amount of time
(seconds).
Unfortunately, [rb-gsl](https://github.com/SciRuby/rb-gsl) is
unmaintained -- there's a commit on main that makes it …

Support Numo Gem for performing SVD

---

docs/index.md

In #198, I added support for using
[Numo::Linalg](https://github.com/ruby-numo/numo-linalg) as the linear
algebra backend for classifier-reborn. At that time, I updated the docs
with instructions for installing Numo, but the macOS docs were a little
vague because I hadn't tested them myself. Since then, I've been able to
verify the instructions on macOS and clarify a few steps. So this commit
updates the docs for installing Numo on macOS. The gem installation
arguments I'm using come from the [Numo
docs](https://github.com/ruby-numo/numo-linalg/blob/master/doc/select-backend.md).

Update macOS instructions in Numo docs

---

classifier-reborn.gemspec

CI has been failing on recent PRs. However, CI passed at the time changes were merged to master. I dug into this problem and found that version 5.x of the redis gem causes CI to fail. Constraining our dependency on the redis gem to `< 5.0` makes CI pass. It seems reasonable to me to merge this restriction, at least for now, since the code that's currently in master clearly doesn't work with redis >= 5.x.

Constrain redis to < 5.0
